services:
- type: web
  name: rs3-discord-bot
  env: node
  plan: free
  buildCommand: npm install
  startCommand: npm start
  envVars:
    - key: BOT_TOKEN
      fromService:
        type: environmentVariable
        name: BOT_TOKEN
    - key: OPENAI_API_KEY
      fromService:
        type: environmentVariable
        name: OPENAI_API_KEY
    - key: ADMIN_API_KEY
      fromService:
        type: environmentVariable
        name: ADMIN_API_KEY